version: '3'
services:
  redis:
    image: redis:3.2-alpine
    command: redis-server
    volumes:
      - egg-redis:/data
    networks:
      - docker_cnode
    ports:
      - 6379:6379

  mongodb:
    image: mongo:3.2
    restart: always
    environment:      
      - MONGO_INITDB_ROOT_USERNAME=vue_club_dev
      - MONGO_INITDB_ROOT_PASSWORD=vue_club_dev
      - MONGO_INITDB_DATABASE=vue_club_dev
      - EGG_REDIS_PASSWORD=vue_club_dev
      - EGG_MONGODB_URL=mongodb://vue_club_dev:vue_club_dev@mongodb:27017/vue_club_dev
    volumes:
      - ./data:/data/db
      - ./init.d/mongo/:/docker-entrypoint-initdb.d/
    networks:
      - docker_cnode
    ports:
      - 27017:27017

volumes:
  egg-redis:

networks:
  docker_cnode:
    driver: bridge    
