version: '3'
services: 
  cnode:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     - env=value
    #     - p=7001:7001
    image: cnode/egg-cnode:latest
    environment:
      - NODE_ENV=production
      - EGG_SERVER_ENV=prod
      - EGG_REDIS_DB=0
      - EGG_REDIS_HOST=redis
      - EGG_REDIS_PORT=6379
      - EGG_REDIS_PASSWORD=egg_cnode
      - MONGO_INITDB_ROOT_USERNAME=vue_club_dev
      - MONGO_INITDB_ROOT_PASSWORD=vue_club_dev
      - MONGO_INITDB_DATABASE=vue_club_dev
      - EGG_REDIS_PASSWORD=vue_club_dev
      - EGG_MONGODB_URL=mongodb://vue_club_dev:vue_club_dev@mongodb:27017/vue_club_dev
      - EGG_MINI_ASSETS=true
      - EGG_PASSPORT_GITHUB_CLIENT_ID=981a5e0bb7aaa4b76443
      - EGG_PASSPORT_GITHUB_CLIENT_SECRET=55d43c59a806d35bf9f055b39725d85c19c9779d
      # - EGG_SITE_STATIC_HOST=${EGG_SITE_STATIC_HOST}
      - EGG_ALINODE_APPID=85328
      - EGG_ALINODE_SECRET=17b232b05a5162b8e8e5ad3dee076f5af7a59887
    depends_on:
      - redis
      - mongodb
    networks:
      - docker_cnode
    ports:
      - 7001:7001

  redis:
    image: redis:3.2-alpine
    command: redis-server 
    volumes:
      - egg-redis:/data
    networks:
      - docker_cnode
    # ports:
    #   - 6379:6379

  mongodb:
    image: mongo:3.2
    restart: always
    environment:      
      - MONGO_INITDB_ROOT_USERNAME=vue_club_dev
      - MONGO_INITDB_ROOT_PASSWORD=vue_club_dev
      - MONGO_INITDB_DATABASE=vue_club_dev
    volumes:
      - ./data:/data/db
      - ./init.d/mongo:/docker-entrypoint-initdb.d
    networks:
      - docker_cnode
    # ports:
    #   - 27017:27017

volumes:
  # egg-mongo:
  egg-redis:

networks:
  docker_cnode:
    driver: bridge    
